name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install specific dependencies
        run: |
          npm install @testing-library/jest-dom@latest --save-dev
          npm install @testing-library/react@latest --save-dev
          npm install jest@latest --save-dev
          npm install webpack@latest --save-dev
          npm install webpack-cli@latest --save-dev

      - name: List files in the work directory
        run: ls -la /home/runner/work/react-github-actions/react-github-actions

      - name: Install dependencies
        run: npm ci --loglevel verbose > npm-install.log 2>&1
        continue-on-error: true

      - name: Display npm install logs
        run: cat npm-install.log

      - name: Build the project
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Deploy to S3
        uses: awact/s3-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: "./build"
          AWS_REGION: "ap-northeast-2"
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
