name: Deploy to AWS

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # 사용할 AWS 리전을 여기 명시하세요
          audience: sts.amazonaws.com

      # AWS 리소스를 배포하거나 상호작용하는 단계 추가
      - name: Deploy to S3
        run: aws s3 sync ./my-website s3://my-bucket --region ap-northeast-2
